### ISSUE TITLE
Allow right-sidebar template

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/byu-humanities-department#1]
[It's already available on the College site](https://github.com/BYU-ODH/byu-humanities-theme/blob/master/page-templates/sidebar-right.php), but one of the departments would like the option for their site.

**Comment by DerekMoss95** [comment]
This was finished on humstaging english repo, just need to finish copying and pasting the exported acf field  and test that a push and pull works on other humstaging sites before deployment to main sites. I will finish this.

**Comment by DerekMoss95** [comment]
As I searched through the acf_byuh.php file for felxible content and sidebar content, it had both. Now it needs to be decided whether to get rid of pre-existing flexible content code and sidebar content code in acf_byuh.php. Will replacing it entirely break it, or do I need to name it something else?

**Comment by DerekMoss95** [comment]
Need permissions to commit, pull, and push on the english repo in order to test the acf_byuh.php working. Insufficient permissions error again.

**Comment by WorldsEndless** [comment]
As a low priority, before any of this is cleaned up you'll need to 
look in to this on the staging site. You'll have to do some 
comprehensive testing to make sure different types of pages aren't 
broken by anything; better might be looking in to the code to see 
when "the_field" calls or similar functions are referencing fields 
from the acf php file.

**Comment by WorldsEndless** [comment]
Permission errors on English humstaging should be fixed now for 
git.

**Comment by DerekMoss95** [comment]
Still not working, this is the error message:

BYU\derekm95@humwp:~/humstaging/english/wp-content/themes/byu-humanities-department$ git commit -a -m "Testing the import of the acf_byuh.php file from spanport"
error: insufficient permission for adding an object to repository database .git/objects
error: advanced-custom-fields/js/field-group.js: failed to insert into database
error: unable to index file advanced-custom-fields/js/field-group.js
fatal: updating files failed

**Comment by DerekMoss95** [comment]
This project has been finished. The correct custom fields have been added to the acf_byuh.php file and correct modifications for the right-sidebar.php have been made. I have committed and pushed them to a different department site where i fetched and pulled those changes and it interacts nicely. Pull request has been made, this issue is fixed and done.
